# Generated by Django 4.1.7 on 2023-05-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usernmae',
            new_name='username',
        ),
    ]
